### ISSUE TITLE
Very high cpu load with enabled animation

### ISSUE THREAD

**Issue by linkurzweg** [webmatze/hyperborder#13]
When I set `animate: true` in the plugin options, the cpu load for Hyper Helper goes crazy.
I'm on MacOS Sierra with hyper v.08.3.
So animation is not usable at the moment. Maybe you could look at this?

![hyperterm](https://cloud.githubusercontent.com/assets/4902517/19939620/14a02914-a12a-11e6-9558-4f4dcbf866ea.png)

**Comment by webmatze** [comment]
Yes, that is a problem with the CSS animations I am using. Seems like the Electron Framework can not handle it in a performant way.

But I am searching for a solution.

Thank you for your report.

**Comment by LukeFlynn** [comment]
I'd just like to add, that the border animation also seems to stress my GPU. I'm running on macOS 10.12.3 (with an Nvidia GTX 660). When playing simple games, my FPS drops in intervals of about 30-40 frames. This is probably also a result of CSS animations with Electron. It's kind of a bummer because it really adds a great look to your terminal!

**Comment by webmatze** [comment]
@LukeFlynn good idea.

**Comment by webmatze** [comment]
@linkurzweg hyperborder should use less CPU now.
Still not optimal, but should be better now.

**Comment by webmatze** [comment]
@LukeFlynn it is now possible to deactivate the border animation while the window is not focused

**Comment by webmatze** [comment]
I am closing this issue as animations can be disabled and use much fewer system resources than before.
