### ISSUE TITLE
Border-radius on Windows

### ISSUE THREAD

**Issue by DanielPintilei** [webmatze/hyperborder#17]
The `border-radius` is not applied on Windows. Also I noticed the `border-radius` on the inner element is the same as on the outer, making the corner border look wider; having the inner radius `1px` less makes the border look the same width; and also, config option for `border-radius` would be nice 😀

**Comment by webmatze** [comment]
Thank you for the heads up on the Windows problem. I haven't tested it there. Although I think, that this is a problem with the Electron framework on Windows. But I will check this.

I don't think subtracting one pixel from the inner border is enough, because it will only look good with a certain border-radius.  I think there is more logic needed.

**Comment by DanielPintilei** [comment]
Yeah, 1px is not enough for funny border widths. Thank you for the awesome work.

**Comment by webmatze** [comment]
This should now be fixed with the latest release of hyperborder. See #46
