### ISSUE TITLE
Width...

### ISSUE THREAD

**Issue by smebberson** [webmatze/hyperborder#21]
The width doesn't seem to change, no matter what I do. I've even edited (just to test) the actual source, and still, the width doesn't change...

I'm on macOS 10.12.3 and Hyper 1.2.1. What stupidity have I committed?

**Comment by webmatze** [comment]
Are you using any other plugins? have you tried to deactivate all of them but hyperborder?

I am running it in the same Hyper version and it works without problems.

Your configuration should look something like this:
```js
...
config: {
  hyperBorder: {
    borderColors: ['#FF0000', '#00FF00','#0000FF']
    borderWidth: '10px'
  }
}
...
```

Maybe you can post your hyper.js configuration so that I can try it on my system.

**Comment by Maamun** [comment]
you have to put the hyperborder object at the top of the config file,  juste below the word config
