### ISSUE TITLE
hyperborder overrides other plugins.

### ISSUE THREAD

**Issue by colshacol** [webmatze/hyperborder#23]
## Expected behavior:
Using `./hyper.js` plugin configuration: `plugins: ['hyperborder', 'hyper-electron-highlighter']`, the `hyper-electron-highlighter` theme should be applied, while the `hyperborder` border effect should remain.

## Actual behavior:
`hyper-electron-highlighter` will not apply its theme if coexisting with `hyperborder` in the plugins configuration. The border applies, though.

## Steps to reproduce:
1. Fresh install `hyper`.
2. Include `hyperborder` and `hyper-electron-highlighter` in the `~/.hyper.js` `plugins` array.
3. Boot up hyper.

**Comment by colshacol** [comment]
Just tested and that `hyperborder` being included after all other plugins works correctly.

Also, I am not deeming this to be an issue with hyperborder. I create this issue more-so to gather knowledge about whether or not this is a known issue and if it may be something I am doing incorrectly.

**Comment by webmatze** [comment]
Thank you @colshacol for your insights on this problem.

`hyperborder` is only changing styles. I don't know what `hyper-electron-highlighter` is doing, but it is possible that it is changing the styles on some of the same elements which might lead to the problems.

I will see if I can find a solution.

**Comment by webmatze** [comment]
As I already answered in the issue #38 ...

The problem here is, that **hyperborder** uses the **backgroundColor** defined in your `.hyper.js` config.

If a theme uses a different background color then you have to change that value to the color used in the theme.

It should also be possible to include **hyperborder** as the last plugin in your plugins list.
